function legDelta = trapz_legDelta(long, shrt, leg, delta)
% calculate corrected leg length for isosceles trapezoid

trap_beta = @(long, shrt, leg, d) ...
    pi/2 + d*asin( ((long-shrt)/2)/leg );

legDelta = sqrt(delta^2 + leg^2 - ...
    2 * abs(delta) * leg * cos( ...
                                trap_beta(long,shrt,leg,sign(delta)) ...
                               ) ...
                );


end